import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { footerColumns } from "@/data/FooterData";
import localFont from 'next/font/local';
import NavBar from "@/components/NavBar";
import GlobalLoader from "./loading";
import { NavData } from "@/data/NavData";

const podcastFont = localFont({
  src: '../assets/fonts/Podcast.ttf', 
  variable: '--font-podcast',
});

const geistSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tuscany",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo/logoWithoutName.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${podcastFont.variable} antialiased `}>
          <GlobalLoader />
          <NavBar logo={"/images/logo/logo.svg"} navData={NavData}/>
          {children}
          <Footer
            columns={footerColumns}
            logoSrc="/images/logo/logo.svg"
            logoAlt="Tuscany Icon"
            year={`© ${new Date().getFullYear()} Tuscany. All rights reserved.`}
          />
      </body>
    </html>
  );
}
